// icerik/makale1.js

export const makaleVerisi = {
  id: 1,
  tarih: "16 MART 2026",
  baslik: "İRAN-ABD SAVAŞINDA SUYUN KARŞI TARAFI",
  ozet: "Körfez ülkelerinin bu savaştaki duruşu üzerine bir komplo teorisi: Marabalıktan yeni dünyanın büyük abiliğine...",
  icerik: `A-)
Birinci kısım: ABD ve İran’ın Ortadoğu genelinde uzun süredir yürüttüğü stratejik hamleler, bölgede kendine has bir siyasi zemin oluşturmuştur. Körfez ülkeleri ise bu süreçte edindikleri yerleşik kanaatler doğrultusunda, olası bir İran-ABD savaşını mevcut dış politika pratiklerinden çok daha farklı ve derin bir düzlemde ele almaktadır. 

Bunun nedenleri tek tek incelenebilir, her bir nedenin üzerinde uzun uzun durulabilir. Ancak yüzyılın ilk çeyreğine yayılmış ve tabiri caizse tarih olmanın kıyısında bulunan bu olaylar dizisi bizi güncel verileri okurken yanıltabilir. 

Dünya kamuoyunun bir şok içerisinde olduğunu söylemek pek mümkün değil. Bu konu oldukça önemli. Zira yıllardır süren bu ABD hegemonyasının ne kadar da içi boş, beş para etmez unsurlara dayandığını şu son dört yılda görmüş olduk. Bence bu gerçek artık bir tartışma konusu değil. Fakat bunun bizi şaşırtması gerektiğini söyleyen birisine karşı çıkmam. Bunun bizi şaşırttığı iddiasını ise kesinlikle yalanlıyorum. Belki de medeniyetimize karşı sergilediği düşmanlık yahut kanımızda akan kuvvet bizdeki sönmek bilmeyen Amerikan düşmanlığını bu günlere taşımıştır. Fakat nedeni ne olursa olsun bugün dünya kamuoyu ezici bir çoğunlukla batıdan ve onun meydana getirdiği son imparatorluktan (ABD) intikam alındığını, hiç olmazsa dünyanın bu eski düzenden kopup daha iyi olacağını umut ettikleri yeni bir düzene sancılı da olsa geçtiğini görmeyi umuyor. 

İşte bu konu özelinde ABD ile zahirde kuvvetli ve tarafları için son derece faydalı gibi görünen körfez- ABD iş birliği marabanın (körfez) içten içe bunalmasıyla sona doğru koşuyor. Komplo teorisinin temelinde bu olgu yatıyor. Savaş gibi sıradan olması gereken (o kadar çok yaşadık ki) bir şey; bu sefer biz insanlık için sadece öfke, keder yahut merak ile takip edeceğimiz bir akşam kuşağı brifingi değildir. Belki de ABD hegemonyasının can damarı petro-dolar sisteminin bizzat kendisi ateş altındadır. İşte tüm bu kaosun büyük israil için bir Siyonist projesi ya da bir şii ekseninin son çırpınışı yahut yeni bir ABD petrol avı olmadığına adım gibi eminim. Peki filler tepişirken fareler ne yapıyor? 

B-)
İkinci kısım: Takvimler 1932 yılında sıkışmışken Kral Abdulaziz öncülüğünde Suudi Arabistan Krallığı kuruldu. Kuruluşunun hangi olaylara müteakiben gerçekleştiği malumunuzdur ve uzun bir meseledir. Bizi ilgilendiren kısmı bu devletin kuruluşundan önce dahi Birleşik Krallık ile arasında ilişki bulunmasıdır. Ve sonrasında Amerikan çıkarları ile bu devletin yolu kesişecektir. Bunlar başka tartışma konularıdır. Bizim tartışmamız daha başka devletler ile Suudi Krallığının buluştuğu noktada başlar. O devletlerden biri Kuveyt’tir. 1961 yılında Birleşik Krallık’a karşı bağımsızlığını elde etmiştir. Ve on yıl sonra 1971’de üç devlet daha marabalar sınıfına katıldılar. 

Tüm bu bağımsızlık edinmeyi takiben dünyada çok önemli bir dizi olay gerçekleşti. Henüz 1973 yılında Arap-İsrail savaşı gerekçesiyle marabalar batıya petrol satmayı reddettiler. İşte bu günümüz İran-ABD savaşına ışık tutan tarihsel bir olgudur. Çünkü bir yıl bile geçmeden bağımsızlığa pek de alışık olmayan körfez ülkeleri petrol ticaretini Amerikan dolarını güçlendirecek şekilde yeniden dizayn ettiler. Bu da ülkelerine Amerikan yatırımı ve güvencesi taşıdı. İşte körfez ülkelerinin göbek bağıyla Amerikan hegemonyasının gölgesinde gelişen dünya sistemine bağlanması böyle gerçekleşti. 71 de İsrail’le savaşan Arap devletleri o tarihten sonra bölgeyi ateşle yakan Siyonist rejime karşı akılda kalır hiçbir önlemde bulunmadılar. 

Dikkat edin, körfezin yükselişi ve ilk defa bir cazibe merkezi haline gelişi son derece riskli ve radikal bir adım olarak bağımsızlıklarını kazanmaları ve bu kazanımın gereği olarak petrol krizini tetiklemiş olmalarıydı. Sonrasında Irak’ta ve İran’da yaşananlar, 2008 ekonomik krizi ve LNG gibi unsurlar körfezi günümüze taşıdı. 

Buraya kadar her şey bize neden onlara körfez ülkeleri ya da marabalar dediğimi açıklamak için yeterlidir. Yıllarca tartışılmaz Amerikan dominyonunu hunharca beslemişlerdir. Fakat dünya ve içindekiler bazen hakkında düşündüğümüz ve sonra da gerçekleştiğini görüp hayrete düştüğümüz bazı hallerden daha öte vahşilerdir. Şimdiye kadar onlara maraba demem belki de garibinize gitmedi ancak bugün bu devletlerin dünya üzerinde gerçekleştirdikleri orta vadeli planların sonuçlarını görüyorsunuz. Bunlar nasıl farelerdir ki filler hem umarsızca tepişir hem de duyarlıca onlara basmak istemez? 

C-)
Sonuç: Kim bir tane daha Yom Kippur Savaşı ister? Savaşları, özellikle günümüz savaşlarını okumanın en doğru yolu aktörlere bakmaktan geçmez. Savaş bize kapsadığı alanın ötesinde de kimlere (devletler, şirketler, kişiler) savaşın öncesinde yapamadıkları neyi o an yapma fırsatı sunar. Adolf Hitler neden Polonya’ya savaş açtı? Polonya ile savaşa girdikten sonra önceden yapmaya muktedir olamadığı ya da yapmasının abes görüneceği ya da yaptığı taktirde birtakım problemlerle karşılaşacağı neleri yapmayı başardı? Bir savaşın tarafları asla o savaşın içinde gafil duruma düşmezler. Savaşı başlatan savaşa en hazır olandır. 

İşte bize tekrar tekrar aynı soruyu sorduran, İsrail devletinin İran rejimini tehdit olarak görmesi olgusu savaşın en basit nedenlerindendir. Tekrar tekrar sorduğumuz soruya gelince: Neden şimdi? Eğer körfez devletleri bir anlamda Amerikan dominyonunda ayrıcalıklı konumda olmayı artık yeterli görmüyor fakat yine de kendileri için faydalı bu sistemi terk ederken bunu sisteme savaş açarak yapmak istemiyorlarsa onu beslemeyi reddetmek yerine kendi kendileri için onu beslemeyi imkânsız hale getirtmeyi istemiş olamazlar mı? 

Kısacası körfez ülkeleri, zaten İran’a saldırmak için can atan Ortadoğu’nun en büyük canlı bombası İsrail’in İran’a giden yolunu açıp üstüne bir de Netenyahu’nun asla tek başına beceremeyeceği şeyi yaparak Trump’ı İran’a saldırmaya ikna etmiş olabilir mi? Savaştan hemen önce 28 şubatta The New York Times’ın iddiası işte bu yöndeydi ve ısrarla Suudi yetkililerce reddedildi. Peki Suudiler bu savaştan önce Çin, Hindistan ve Rusya ile yapamadıklarını savaştan sonra yapmaya başlayabilecekler mi? Birbirleri söz konusu olduğunda bu devletler azılı birer düşmanken azılı birer düşman ya da dost olabilme imkanı söz konusu olduğunda ilerine dış dünyanın karışmaması için son derece müşterek hareket eden yapılardır bu “marabalar”. Ve artık “maraba” olmaktan çok öte yeni dünyanın büyük abileri olmaya hazırlanıyorlar…`
};